# Copyright (C) 2020 Panther Labs Inc
#
# Panther Enterprise is licensed under the terms of a commercial license available from
# Panther Labs Inc ("Panther Commercial License") by contacting contact@runpanther.com.
# All use, distribution, and/or modification of this software, whether commercial or non-commercial,
# falls under the Panther Commercial License to the extent it is permitted.

on:
  pull_request:
    branches:
      - master
      - release-*
    types:
      - opened
      - closed

jobs:
  update_task_on_pr_open:
    if: ${{ github.event.pull_request.state == 'open' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout Repo

      - uses: ./
        name: Adds a comment to the related Asana task whenever a PR has been opened
        with:
          asana-pat: ${{ secrets.ASANA_PAT }}
          action: 'add-comment'
          text: ${{ format('A Pull Request has been opened {0}', github.event.pull_request.html_url) }}
          is-pinned: true

      - uses: ./
        name: Moves the Asana task to "In Review" when the PR is opened
        with:
          asana-pat: ${{ secrets.ASANA_PAT }}
          action: 'move-section'
          targets: '[{"projectNameRegex": "(S|s)print", "section": "In Review"}]'

  update_task_on_pr_close:
    if: ${{ github.event.pull_request.state == 'closed' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout Repo

      - uses: ./
        name: For non-release branches, adds a comment to the related Asana task when the PR is closed
        if: startsWith(github.event.pull_request.base.ref, 'release-') != true
        with:
          asana-pat: ${{ secrets.ASANA_PAT }}
          action: 'add-comment'
          text: ${{ format('A Pull Request is now closed {0}', github.event.pull_request.html_url) }}
          is-pinned: true

      - name: Read version file in release branches
        if: startsWith(github.event.pull_request.base.ref, 'release-') == true
        id: version
        run: echo "::set-output name=version::$(cat demo/example_files_in_repo/VERSION)"

      - uses: ./
        name: Adds a comment to the Asana task with a version number when in release branches
        if: startsWith(github.event.pull_request.base.ref, 'release-') == true
        with:
          asana-pat: ${{ secrets.ASANA_PAT }}
          action: 'add-comment'
          text: ${{ format('A Pull Request is now merged to {0} {1}', steps.version.outputs.version,
                           github.event.pull_request.html_url) }}
          is-pinned: true

      - uses: ./
        name: Closes the related Asana tasks when the PR gets merged
        if: github.event.pull_request.merged
        with:
          asana-pat: ${{ secrets.ASANA_PAT }}
          action: 'complete-task'
          trigger-phrase-regex: '(c|C)loses'
          is-complete: true
